module.exports = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    practiceArea: "Intellectual Property Rights",
    serviceType: "Patents",
    isExistingClient: "no",
    communicationMode: "email",
    message: "I have an invention I would like to patent.",
    status: "New",
    submittedAt: new Date("2024-07-10T10:00:00Z"),
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "098-765-4321",
    practiceArea: "Corporate and Commercial Law",
    serviceType: "Mergers & Acquisitions",
    isExistingClient: "yes",
    communicationMode: "phone",
    message: "Looking for legal advice on a potential acquisition.",
    status: "New",
    submittedAt: new Date("2024-07-11T14:30:00Z"),
  },
  {
    name: "Peter Jones",
    email: "peter.jones@example.com",
    phone: "555-555-5555",
    practiceArea: "Real Estate Law",
    serviceType: "Property Transactions",
    isExistingClient: "no",
    communicationMode: "email",
    message: "I need help with the legal paperwork for buying a new house.",
    status: "Contacted",
    submittedAt: new Date("2024-07-12T09:00:00Z"),
  },
];
